// Original vector art, pixel creature and font. No original Monster Maze assets.
const fs=require('fs');
const path=require('path');
module.exports=function generate(root){
let out='; Generated by tools/assets.cjs. Edit the generator, then npm run build.\n';
const db=(a)=>{for(let i=0;i<a.length;i+=24)out+=' db '+a.slice(i,i+24).join(',')+'\n';};
const emit=(n,a)=>{out+=n+':\n';db(a);};
let pix;
function clear(){pix=new Uint8Array(256*128)}
function dot(x,y){x=Math.round(x);y=Math.round(y);if(x>=0&&x<256&&y>=0&&y<128)pix[y*256+x]=1;}
function line(x,y,X,Y){const n=Math.max(Math.abs(X-x),Math.abs(Y-y));for(let i=0;i<=n;i++)dot(x+(X-x)*i/(n||1),y+(Y-y)*i/(n||1));}
function poly(p){for(let i=0;i<p.length;i++)line(...p[i],...p[(i+1)%p.length]);}
function sprite(name){const a=[];for(let y=0;y<128;y++){let row=[];for(let x=0;x<32;x++){let b=0;for(let k=0;k<8;k++)b=b*2+pix[y*256+x*8+k];row.push(b)}let x=0;while(x<32){while(x<32&&!row[x])x++;if(x===32)break;let s=x;while(x<32&&row[x])x++;a.push((y*32+s)&255,(y*32+s)>>8,x-s,...row.slice(s,x));}}a.push(0,255);emit(name,a);if(/^(monster|seal|exit)_\d$/.test(name)){let cells=new Set;for(let y=0;y<128;y++)for(let x=0;x<256;x++)if(pix[y*256+x])cells.add(22528+((y>>3)+2)*32+(x>>3));out+=name.replace(/_(\d)$/,'_attr_$1')+': dw '+[...cells,0].join(',')+'\n';}}
const xs=[0,40,80,104,116],ys=[0,24,44,54,60];
for(let d=0;d<4;d++)for(let side=0;side<2;side++)for(let open=0;open<2;open++){
 clear();let x=xs[d],X=xs[d+1],y=ys[d],Y=ys[d+1];const tr=(a)=>side?255-a:a;
 if(!open){poly([[tr(x),y],[tr(X),Y],[tr(X),127-Y],[tr(x),127-y]]);for(let t=1;t<4;t++){let y1=y+(127-2*y)*t/4,y2=Y+(127-2*Y)*t/4;line(tr(x),y1,tr(X),y2);let xx=x+(X-x)*(t%2?0.36:0.68),u=(xx-x)/(X-x),top=y+(Y-y)*u,h=127-2*top;line(tr(xx),top+h*(t-1)/4,tr(xx),top+h*t/4);}}
 else {line(tr(x),y,tr(x),127-y);line(tr(X),Y,tr(X),127-Y);line(tr(x),Y,tr(X),Y);line(tr(x),127-Y,tr(X),127-Y);for(let yy=Y+3;yy<127-Y;yy+=6)dot(tr(X+(side?0:-1)),yy);}
 sprite(`side_${d}_${side}_${open}`);
}
for(let d=0;d<4;d++){
clear();let x=xs[d+1],y=ys[d+1],w=255-2*x,h=127-2*y;poly([[x,y],[255-x,y],[255-x,127-y],[x,127-y]]);const step=Math.max(4,Math.round(h/4));for(let yy=y+step, row=0;yy<127-y;yy+=step,row++){line(x,yy,255-x,yy);let bw=Math.max(6,Math.round(w/4));for(let xx=x+bw*(row%2?0.5:1);xx<255-x;xx+=bw)line(xx,yy-step,xx,yy);}sprite('front_'+d);
}
const beast=[
'....##........##....','...####......####...','...##############...','..################..','..###..######..###..','..###..######..###..','..################..','...##############...','....##.#.##.#.##....','....#.#.#..#.#.#....','.....##########.....','..################..','.##################.','####.##########.####','###..##########..###','###..##########..###','##...##########...##','##....########....##','#.....########.....#','......###..###......','.....####..####.....','....#####..#####....'];
for(let d=0;d<4;d++){
 clear();const scale=[3,2,1,0.5][d];for(let y=0;y<beast.length;y++)for(let x=0;x<20;x++)if(beast[y][x]==='#')for(let j=0;j<Math.max(1,scale);j++)for(let i=0;i<Math.max(1,scale);i++)dot(128+(x-10)*scale+i,64+(y-10)*scale+j);sprite('monster_'+d);
 const mask=new Uint8Array(pix.length);for(let y=1;y<127;y++){let x1=256,x2=-1;for(let x=0;x<256;x++)if(pix[y*256+x]){x1=Math.min(x1,x);x2=Math.max(x2,x)}for(let x=x1-1;x<=x2+1;x++)for(let yy=y-1;yy<=y+1;yy++)if(x>=0&&x<256)mask[yy*256+x]=1;}
 const erase=[];for(let y=0;y<128;y++){let row=[];for(let x=0;x<32;x++){let b=0;for(let k=0;k<8;k++)b=b*2+mask[y*256+x*8+k];row.push(b)}let x=0;while(x<32){while(x<32&&!row[x])x++;if(x===32)break;let s=x;while(x<32&&row[x])x++;erase.push((y*32+s)&255,(y*32+s)>>8,x-s,...row.slice(s,x).map(v=>v^255));}}erase.push(0,255);emit('monster_erase_'+d,erase);
 clear();let r=[13,9,6,3][d];poly([[128,64-r],[128+r,64],[128,64+r],[128-r,64]]);line(128-r/2,64,128+r/2,64);line(128,64-r/2,128,64+r/2);sprite('seal_'+d);
 clear();let w=[18,12,7,4][d],h=w*1.6;poly([[128-w,64-h],[128+w,64-h],[128+w,64+h],[128-w,64+h]]);line(128,64-h+3,128,64+h-3);line(128,64-h+3,123,64-h+9);line(128,64-h+3,133,64-h+9);sprite('exit_'+d);
}
out+='side_table:\n';for(let d=0;d<4;d++)out+=' dw '+[0,1].flatMap(s=>[0,1].map(o=>`side_${d}_${s}_${o}`)).join(',')+'\n';
for(const n of ['front','monster','monster_erase','seal','exit','monster_attr','seal_attr','exit_attr'])out+=n+'_table: dw '+[0,1,2,3].map(d=>n+'_'+d).join(',')+'\n';
// Three reproducible perfect mazes plus loops; boundaries remain sealed.
for(let seed=1;seed<=3;seed++){
 let state=seed*9187;const rand=n=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state%n};let m=Array(256).fill(1);m[17]=0;let stack=[17];while(stack.length){let p=stack.at(-1),ns=[-32,2,32,-2].filter(v=>{let t=p+v;return t>16&&t<239&&(t&15)>0&&(t&15)<15&&m[t]===1});if(!ns.length){stack.pop();continue}let v=ns[rand(ns.length)];m[p+v/2]=0;m[p+v]=0;stack.push(p+v)}
 for(let i=0;i<9;i++){let cand=[];for(let p=17;p<239;p++)if((p&15)>0&&(p&15)<15&&m[p]&&((m[p-1]===0&&m[p+1]===0)||(m[p-16]===0&&m[p+16]===0)))cand.push(p);if(cand.length)m[cand[rand(cand.length)]]=0;}
 const dist=s=>{let q=[s],d=Array(256).fill(999);d[s]=0;for(let p of q)for(let v of [-16,1,16,-1])if(!m[p+v]&&d[p+v]===999){d[p+v]=d[p]+1;q.push(p+v)}return d};
 let dd=dist(17),order=m.map((v,p)=>p).filter(p=>!m[p]).sort((a,b)=>dd[b]-dd[a]);let exit=order[0],monster=order.find(p=>dd[p]>=20&&p!==exit);let picks=[exit];for(let i=0;i<3;i++){let distances=picks.map(dist);let p=order.filter(p=>p!==17&&p!==monster&&!picks.includes(p)).sort((a,b)=>Math.min(dd[b],...distances.map(d=>d[b]))-Math.min(dd[a],...distances.map(d=>d[a])))[0];picks.push(p)}
 m[exit]=3;for(let p of picks.slice(1))m[p]=2;
 emit('maze_'+(seed-1),m);emit('spawn_'+(seed-1),[monster]);
}
out+='maze_table: dw maze_0,maze_1,maze_2\nspawn_table: db '; // filled from previous records
const matches=[...out.matchAll(/spawn_\d:\n db (\d+)/g)];out+=matches.map(m=>m[1]).join(',')+'\n';
const alphabet={
' ':['00000','00000','00000','00000','00000','00000','00000'],
A:['01110','10001','10001','11111','10001','10001','10001'],B:['11110','10001','10001','11110','10001','10001','11110'],C:['01111','10000','10000','10000','10000','10000','01111'],D:['11110','10001','10001','10001','10001','10001','11110'],E:['11111','10000','10000','11110','10000','10000','11111'],F:['11111','10000','10000','11110','10000','10000','10000'],G:['01111','10000','10000','10111','10001','10001','01111'],H:['10001','10001','10001','11111','10001','10001','10001'],I:['11111','00100','00100','00100','00100','00100','11111'],J:['00111','00010','00010','00010','10010','10010','01100'],K:['10001','10010','10100','11000','10100','10010','10001'],L:['10000','10000','10000','10000','10000','10000','11111'],M:['10001','11011','10101','10101','10001','10001','10001'],N:['10001','11001','10101','10011','10001','10001','10001'],O:['01110','10001','10001','10001','10001','10001','01110'],P:['11110','10001','10001','11110','10000','10000','10000'],Q:['01110','10001','10001','10001','10101','10010','01101'],R:['11110','10001','10001','11110','10100','10010','10001'],S:['01111','10000','10000','01110','00001','00001','11110'],T:['11111','00100','00100','00100','00100','00100','00100'],U:['10001','10001','10001','10001','10001','10001','01110'],V:['10001','10001','10001','10001','10001','01010','00100'],W:['10001','10001','10001','10101','10101','10101','01010'],X:['10001','10001','01010','00100','01010','10001','10001'],Y:['10001','10001','01010','00100','00100','00100','00100'],Z:['11111','00001','00010','00100','01000','10000','11111'],
'0':['01110','10001','10011','10101','11001','10001','01110'],'1':['00100','01100','00100','00100','00100','00100','01110'],'2':['01110','10001','00001','00010','00100','01000','11111'],'3':['11110','00001','00001','01110','00001','00001','11110'],'4':['00010','00110','01010','10010','11111','00010','00010'],'5':['11111','10000','10000','11110','00001','00001','11110'],'6':['01110','10000','10000','11110','10001','10001','01110'],'7':['11111','00001','00010','00100','01000','01000','01000'],'8':['01110','10001','10001','01110','10001','10001','01110'],'9':['01110','10001','10001','01111','00001','00001','01110'],
'-':['00000','00000','00000','11111','00000','00000','00000'],':':['00000','00100','00100','00000','00100','00100','00000'],'/':['00001','00001','00010','00100','01000','10000','10000'],'.':['00000','00000','00000','00000','00000','00100','00100'],'!':['00100','00100','00100','00100','00100','00000','00100']};
const font=[];for(let c=32;c<91;c++)font.push(0,...(alphabet[String.fromCharCode(c)]||alphabet[' ']).map(r=>parseInt(r,2)<<2));emit('font',font);
fs.writeFileSync(path.join(root,'assets.inc'),out);
};
